name: DiscordWhitelister
version: 1.0.2
author: Joe Shimell
main: uk.co.angrybee.joe.DiscordWhitelister
description: Discord whitelister bot.

permissions:
  discordbot:
    description: discordbot permission.
    default: true